Jdp200303 21
metho/project-jdp-2003-03 pull request #26
Opened 2020-04-01 16:24 UTC by Aleks0491

Implementacja ProductController

2020-04-04 13:17 UTC, binkul commented
> 
> 
> Implementacja ProductController

Trochę dużo tu commitów - ja bym raczej nie ruszał encji Product, ProductGroup i testów. Według mnie na obecną chwilę na masterze są dobre, gardle przechodzi. Prawdopodobnie zrobiłeś w którymś momencie merga mastera do swojej gałęzi, jak jeszcze był ten ogólny błąd Product z testami. Teraz jest czysto. Może Michał niech doradzi, ale chyba trzeba by było zrobić jeszcze raz merga mastera do gałęzi i rozwiązać konflikty na korzyść mastera??? Co do reszty pare uwag

2020-04-04 14:01 UTC, binkul requested changes

2020-04-04 14:01 UTC, binkul commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
>  @RequestMapping("/v1/products")
Może '/v1/product' - wszystkie pozostałe controlery używają liczby pojedynczej

2020-04-04 14:01 UTC, binkul commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +        return productMapper.mapToProductDto(productService.getProduct(productId).orElseThrow(ProductNotFoundException::new));
Ten błąd wyrzucałbym w serwisie, nie tutaj,

2020-04-04 14:01 UTC, binkul commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +    public void deleteProduct(Long productId) throws ProductNotFoundException {
ten błąd jak wyżej przenieść na etap serwisu

2020-04-04 14:01 UTC, binkul commented on src/main/java/com/kodilla/ecommercee/exception/ProductNotFoundException.java
> +public class ProductNotFoundException extends Exception {
jak dasz RuntimeException nie będziesz musiał się przerzucać z throws... w deklaracjach metod. Ale może rozważysz użycie ogólnego błędu, który już istnieje w projekcie - EntityNotFoundException("Opis błędu - np. Product not found.")?

2020-04-04 14:01 UTC, binkul commented on src/main/java/com/kodilla/ecommercee/mapper/ProductMapper.java
> +                product.getYear());
Może to mi umknęło przy tylu commitach, ale ProductDto musi mieć pole ProductGroupDto groupDto, inaczej z Postmana nie będziemy mogli utworzyć produktu, bo nie dostaniemy groupId (a musi być). Poza tym mappery są dobre.

2020-04-04 14:01 UTC, binkul commented on src/main/java/com/kodilla/ecommercee/repository/ProductRepository.java
> +    //Optional<Product> findByName();
To by mogło zostać odkomentowane, w przypadku produktu całkiem możliwe, że będziemy go chcieli znaleźć po nazwie (w nawiasie brakuje 'String name'). Trzeba by wtedy do controllera dodać nowy endpoint. Jeśli jednak nie, to komentarze usuwamy,

2020-04-04 14:01 UTC, binkul commented on src/main/java/com/kodilla/ecommercee/service/ProductService.java
> +        return productRepository.findById(productId);
Tu wyrzuciłbym błąd 'notfound', nie popychał Optional dalej

2020-04-04 14:01 UTC, binkul commented on src/main/java/com/kodilla/ecommercee/service/ProductService.java
> +        return productRepository.save(product);
A co jeśli taki product już istnieje w bazie - zdublujemy go. Należałoby sprawdzić przed zapisem, czy product o takiej nazwie, kraju pochodzenia, brand, model już jest w bazie i wyrzucić wyjątek EntityAlreadyExistException(). JpaRepository ma fajne metody typu 'boolean existByNameAnd...' - można to wykorzystać. Wtedy trzeba wyodrębnić osobna metode updateProduct dla PUT

2020-04-04 14:01 UTC, binkul commented on src/main/java/com/kodilla/ecommercee/service/ProductService.java
> +         productRepository.deleteById(productId);
Delete według mnie jest zawsze najtrudniejsze do zrobienia. Nie można usuwać z bazy danych Product, który został wykorzystany do jakiś Items (czyli do sprzedaży) - bo skarbówka wejdzie nam na głowę. Delete na produkcie można zrobić tylko wtedy, kiedy nie został użyty nigdzie w żadnym Item. Ja byłbym nawet za tym (ale to do przegłosowania przez wszystkich), żeby niczego nie usuwać, a każda encja miała specjalne pole 'deleted', którego ustawienie na true powoduje, że taki rekord został usunięty (ale nie fizycznie)

2020-04-13 17:25 UTC, Aleks0491 commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
>  @RequestMapping("/v1/products")
ok, niech tak będzie, żeby wyglądało to spójnie

2020-04-13 17:29 UTC, Aleks0491 commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +        return productMapper.mapToProductDto(productService.getProduct(productId).orElseThrow(ProductNotFoundException::new));
słuszna uwaga, będzie to bardziej przejrzyste

2020-04-13 17:32 UTC, Aleks0491 commented on src/main/java/com/kodilla/ecommercee/exception/ProductNotFoundException.java
> +public class ProductNotFoundException extends Exception {
postanowiłem wykorzystać EnityNotFoundException, wygląda na to, że klasę ProductNotFoundException będzie można całkiem usunąć

2020-04-13 17:34 UTC, Aleks0491 commented on src/main/java/com/kodilla/ecommercee/repository/ProductRepository.java
> +    //Optional<Product> findByName();
dzięki za podpowiedź: " (w nawiasie brakuje 'String name')" - tego nie wiedziałem

2020-04-22 22:39 UTC, closed without merging