order controller with mocktests
metho/project-jdp-2003-03 pull request #4
Opened 2020-03-25 17:04 UTC by KariFra

Przesyłam po poprawie. I czekam na kolejne uwagi.

2020-03-25 19:12 UTC, metho requested changes

2020-03-25 19:12 UTC, metho commented on build.gradle
> +    compile group: 'org.apache.tomcat', name: 'tomcat-jdbc', version: '7.0.28'
Do czego jest potrzebne to dependency? Prawdopodobnie ono powoduje problem z testami

2020-03-25 19:12 UTC, metho commented on src/main/java/com/kodilla/ecommercee/DbServiceOrder.java
> +public class DbServiceOrder {
Proponował bym nazwy serwisów na zasadzie <NazwaObiektu>Service. Np OrderService

2020-03-25 19:12 UTC, metho commented on src/main/java/com/kodilla/ecommercee/DbServiceOrder.java
> +    public Optional<Order> getOrderMock(Long orderId) {
W tym podejściu z mockami chodziło raczej o to, żeby Controller na razie tworzył mockowe dane podobnie jak w module z TaskControllerem. Takie mieszanie osobnej klasy do mocków z serwisem nie jest najlepszym pomysłem,

2020-03-25 19:12 UTC, metho commented on src/main/java/com/kodilla/ecommercee/OrderMapper.java
> +    private OrderDto orderDto;
Te dwie zmienne chyba nie są tutaj do niczego potrzebne

2020-03-25 19:12 UTC, metho commented on src/main/java/com/kodilla/ecommercee/OrderMapper.java
> +    public List<OrderDto> translateToOrderList(List<Order> orders){
Jeśli mamy już mapper dla pojedyńczego elementu(translateToOrderDto), to wykorzystajmy go w mapowaniu elementów listy zamiast dopisywać drugi raz kod do mapowania. Jeśli pojawi się więcej pól będzie tam dużo powtórzeń

2020-03-25 19:12 UTC, metho commented on src/main/java/com/kodilla/ecommercee/OrderMock.java
> +public interface OrderMock {
Ten mock nam nie jest tak naprawdę potrzebny. Wystarczy stworzyć mockowe dane w Controllerze na ten moment

2020-03-26 11:05 UTC, KariFra commented
Poprawiłam zgodnie ze wskazówkami

2020-03-26 16:08 UTC, closed without merging