Remove displaying password v.2
metho/project-jdp-2003-03 pull request #42
Opened 2020-04-23 18:50 UTC by kaczorowski91

2020-04-26 10:15 UTC, binkul requested changes

2020-04-26 10:15 UTC, binkul commented on src/main/java/com/kodilla/ecommercee/mapper/UserMapper.java
> +    public UserDto mapToUserDtoExternal(final User user) {
Ok, działa, ale tylko w Get{id} i Get{all}. PUT i POST nadal zwracają odkryte hasło,

2020-04-27 20:35 UTC, kaczorowski91 commented on src/main/java/com/kodilla/ecommercee/mapper/UserMapper.java
> +    public UserDto mapToUserDtoExternal(final User user) {
ok, będę poprawiał

2020-05-04 18:17 UTC, binkul commented on src/main/java/com/kodilla/ecommercee/mapper/UserMapper.java
> +    public UserDto mapToUserDtoExternal(final User user) {
Teraz wygląda ok,

2020-05-04 18:18 UTC, binkul approved these changes

2020-05-10 07:49 UTC, merged