Product controller implementation
metho/project-jdp-2003-03 pull request #44
Opened 2020-05-10 13:13 UTC by kaczorowski91

2020-05-11 08:45 UTC, binkul requested changes

2020-05-11 08:45 UTC, binkul commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +    @GetMapping("/{id}")
Albo piszemy 'value =' (jak niżej), albo nie piszemy nigdzie,

2020-05-11 08:45 UTC, binkul commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +    @GetMapping(value = "/{name}")
Albo piszemy 'value = ' albo nie piszemy nigdzie (patrz pietro wyżej).
Get byId(patrz wyżej) i Get byName mają ten sam URL bazowy ('/v1/product/'). Wyrzuca błąd, bo java nie wie, którego endpointa użyć. Trzeba je jakoś rozróżnić, np: tutaj dać:
@GetMapping("/byname")
public void getProduct(@RequestParam("name") String name) { ....
-> wtedy nasz URL dla tego endpoinat będzie '/v1/product/byname?name=costam'

2020-05-11 08:45 UTC, binkul commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +        return productMapper.mapToProductDto(productService.updateProduct(productMapper.mapToProduct(productDto)));
Ta linijka jest nieco zagmatwana. To owszem działa, ale na przyszłość można by pomyśleć jak to poskracać

2020-05-11 08:45 UTC, binkul commented on src/main/java/com/kodilla/ecommercee/dto/ProductDto.java
> +        this.description = description;
Obcięte nieco za dużo. ProductDto musi mieć jakąś wskazówkę, do której ProducyGroup należy (tam jest relacja wiele do jednego). Na górze jest Long groupId, więc tu brakuje 
this.groupId = groupId

2020-05-11 08:45 UTC, binkul commented on src/main/java/com/kodilla/ecommercee/mapper/ProductMapper.java
> +                        .orElseThrow(() -> new EntityNotFoundException(ExceptionType.GROUP_NOT_FOUND, productDto.getId().toString())));
Tu bym tego nie dawał. Przy tworzeniu instancji klasy przekazujemy parametry, nie robimy dodatkowej logiki w parametrach.
W ProductGroupService jest metoda 'getGroupOrException' więc zaraz pod definicją metody dałbym:
ProductGroup productGroup = service.getGroupOrException(productDto.getGroup_id())
a potem w tym miejscu po prostu productGroup;
Trzeba tylko wstrzyknąć pod klasą ProductGroupService zamaist bawić się w repo,

2020-05-11 08:45 UTC, binkul commented on src/main/java/com/kodilla/ecommercee/repository/ProductRepository.java
> +    Object existsByNameAndBrandAndModelAndYear(String name, String brand, String model, int year);
zamiast Object powinno być boolean (ta metoda zwraca true lub false)

2020-05-11 08:45 UTC, binkul commented on src/main/java/com/kodilla/ecommercee/service/ProductService.java
> +                .equals(product)) {
exist... zwraca boolean (true lub false), więc dalsze equals są tu niepotrzebne.

2020-05-11 11:31 UTC, kaczorowski91 commented on src/main/java/com/kodilla/ecommercee/service/ProductService.java
> +                .equals(product)) {
Poprawione wszystko, możesz zerknąć :)

2020-05-16 16:39 UTC, binkul requested changes

2020-05-16 16:39 UTC, binkul commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
>      public void deleteProduct(Long productId) {
Brakuje @PathVariable

2020-05-16 16:39 UTC, binkul commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
>      @DeleteMapping
Brakuje (/{id})

2020-05-16 16:39 UTC, binkul commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +    @GetMapping("/byname/{name}")
name to nie id. Lepsza jest ścieżka url typu: "...../byname?name=costam"
Tu lepiej dać @GetMapping("/byname"), a niżej:
getProduct(@RequestParam("name") String name) { ....

2020-05-16 16:39 UTC, binkul commented on src/main/java/com/kodilla/ecommercee/mapper/ProductMapper.java
> +    public Product mapToProduct(final ProductDto productDto) {
Całość działa, ale trzeba to rozbić:
Tu powinno się znaleźć to co jest niżej
ProductGroup productGroup = productGroupService.getGroupOrException(productDto.getGroupId())

2020-05-16 16:39 UTC, binkul commented on src/main/java/com/kodilla/ecommercee/mapper/ProductMapper.java
> +        ProductGroup productGroup = productGroupService.getGroupOrException(productDto.getGroupId());
A tu zamiast tego tylko 
productGroup;

2020-05-18 19:19 UTC, binkul approved these changes

2020-05-18 19:19 UTC, merged