GroupProduct entity implementation
metho/project-jdp-2003-03 pull request #8
Opened 2020-03-26 11:42 UTC by binkul

Co prawda tu powinna być relacja jeden-wiele z encją Product (od strony Product musi być), ale według mnie nie jest konieczna. Jeśli ktoś będzie chciał pobrać wszystkie produkty danej Grupy, wystarczy id Grupy. O ile wiem, relacje jednostronne są dopuszczalne.
Dodałem tez zmodyfikowanego Gradla, bo poprzednio zapomniałem i nie przechodził Circleci ze względu na brak Lomboka ...

2020-03-26 15:24 UTC, metho requested changes
Można zrobić relacje jednostronną, natomiast pytanie czemu taką robić w tym wypadku? Pewnie będziemy się chcieli potencjalnie odwoływać do Groupy z jej produktami i będzie nam wygodniej jak będzie taka relacja.

2020-03-26 15:24 UTC, metho commented on src/main/java/com/kodilla/ecommercee/entity/GroupProduct.java
> +public class GroupProduct {
Proponuje to nazwać ProductGroup zamiast GroupProduct (co może też  po angielsku oznaczać "pogrupuj product")

2020-03-26 19:07 UTC, binkul reviewed
dodałem chwilowa 'zaślepkę' w postaci encji ProductMock, bo encja Product nie jest jeszcze gotowa. Potem się ja usunie i poprawi pole w ProductGroup

2020-03-27 08:40 UTC, metho approved these changes
Dwie drobne uwagi. Jak poprawisz możesz wrzucać bez czekania na kolejne review

2020-03-27 08:40 UTC, metho commented on src/main/java/com/kodilla/ecommercee/entity/ProductMock.java
> +public class ProductMock {
Nazwij to po prostu Product, Ktoś kto będzie miał zadanie na Product po prostu uzupelni resztę pól

2020-03-27 08:40 UTC, metho commented on src/main/java/com/kodilla/ecommercee/entity/ProductGroup.java
> +                fetch = FetchType.LAZY)
FetchType.LAZY jest domyślny dla mapowania @OneToMany nie trzeba go podawać

2020-03-27 09:38 UTC, merged